In [1]:
%matplotlib inline

In [2]:
import torch
import numpy as np

In [3]:
# from pure python list to tensor
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(f"Tensor from python list: {x_data} \n")

Tensor from python list: tensor([[1, 2],
        [3, 4]]) 



In [4]:
# from numpy array to tensor
np_array = np.array(data, dtype=np.float32)
x_np = torch.from_numpy(np_array)
print(f"Tensor from numpy array: {x_np} \n")

Tensor from numpy array: tensor([[1., 2.],
        [3., 4.]]) 



In [5]:
x_ones = torch.ones_like(x_data)  # retains the properties of x_data
print(f"Ones Tensor: {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)  # overrides the datatype of x_data
print(f"Random Tensor: {x_rand} \n")

Ones Tensor: tensor([[1, 1],
        [1, 1]]) 

Random Tensor: tensor([[0.5526, 0.1651],
        [0.9284, 0.1497]]) 



In [6]:
tensor = torch.rand(3, 4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [7]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

In [9]:
torch.cuda.is_available()

False

In [10]:
tensor = torch.ones(4, 4)
print('First row: ',tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [11]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [12]:
# 2つのテンソル行列のかけ算です。 y1, y2, y3 は同じ結果になります。
y1 = tensor @ tensor.T
print("y1 = tensor @ tensor.T", y1)

y2 = tensor.matmul(tensor.T)
print("y2 = tensor.matmul(tensor.T)", y2)

y3 = torch.rand_like(tensor)
print("y3 = torch.rand_like(tensor)", y3)

torch.matmul(tensor, tensor.T, out=y3)


y1 = tensor @ tensor.T tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
y2 = tensor.matmul(tensor.T) tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
y3 = torch.rand_like(tensor) tensor([[0.8633, 0.9901, 0.6962, 0.5940],
        [0.4449, 0.7768, 0.5253, 0.2163],
        [0.9394, 0.4552, 0.8630, 0.1562],
        [0.3538, 0.2212, 0.6515, 0.2557]])


tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [13]:
# こちらは、要素ごとの積を求めます。 z1, z2, z3 は同じ値になります。
z1 = tensor * tensor
print("z1 = tensor * tensor", z1)

z2 = tensor.mul(tensor)
print("z2 = tensor.mul(tensor)", z2)

z3 = torch.rand_like(tensor)
print("z3 = torch.rand_like(tensor)", z3)

torch.mul(tensor, tensor, out=z3)

z1 = tensor * tensor tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
z2 = tensor.mul(tensor) tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
z3 = torch.rand_like(tensor) tensor([[0.2816, 0.5677, 0.6833, 0.7047],
        [0.9448, 0.7675, 0.6975, 0.0818],
        [0.2153, 0.1823, 0.3255, 0.7677],
        [0.2152, 0.9168, 0.7795, 0.7579]])


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [14]:
# 1要素のテンソル（テンソルの全要素を足し算する等をした結果生まれます）を扱う場合には、.item()を使用することでPythonの数値型変数に変換できます。
agg = tensor.sum()
print("agg = tensor.sum()", agg)

agg_item = agg.item()
print(agg_item, type(agg_item))

agg = tensor.sum() tensor(12.)
12.0 <class 'float'>


In [15]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


【注意】

インプレース操作はメモリを節約できますが、演算履歴が失われてしまうため、微分を計算する際には問題となります。

そのため、そのような微分を求める場面ではインプレース操作の使用は推奨されていません。

In [16]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [17]:
# この際、テンソルが変化すると、Numpy側も変化します。
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [18]:
# NumPy arrayの変化はテンソル側にも反映されます。
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([3., 3., 3., 3., 3.])
n: [3. 3. 3. 3. 3.]
